# Generated by Django 5.2.4 on 2025-07-28 08:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='question_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='usersession',
            name='current_question_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersession',
            name='current_trait',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='section',
            field=models.CharField(default='big5', max_length=50),
        ),
    ]
