# Generated by Django 5.2.4 on 2025-07-28 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_answer_created_at_question_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer_text',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='ai_category',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='ai_score',
        ),
        migrations.RemoveField(
            model_name='question',
            name='section',
        ),
        migrations.AddField(
            model_name='answer',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='assessment_type',
            field=models.CharField(default='big_five', max_length=50),
        ),
        migrations.AddField(
            model_name='usersession',
            name='current_assessment',
            field=models.CharField(default='big_five', max_length=50),
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_type', models.CharField(max_length=50)),
                ('trait', models.CharField(max_length=50)),
                ('total_score', models.IntegerField(default=0)),
                ('level', models.CharField(default='modéré', max_length=20)),
                ('analysis', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.usersession')),
            ],
        ),
    ]
