# Generated by Django 5.2.4 on 2026-01-06 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("APP", "0002_remove_participant_email_remove_participant_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="report_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
